---
- name: deploy spring petclinic
  become: yes
  hosts: appserver
  gather_facts: yes
  tasks:
    - name: bail out if running on unsupported os
      ansible.builtin.fail:
        msg: "This playbook supports only ubuntu and redhat distribution"
      when: ansible_facts['distribution'] != 'Ubuntu' and ansible_facts['distribution'] != 'RedHat'
    - name: print info
      ansible.builtin.debug:
        msg: Java Package name is {{ java_package }}
    - name: install openjdk 17
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
    - name: create spc user
      ansible.builtin.user:
        name: "{{ username }}"
        create_home: yes
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
    - name: download jar into spc home directory
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ destination }}"
        owner: "{{ username }}"
    - name: copy the service file
      ansible.builtin.copy:
        src: spc.service
        dest: "/usr/lib/systemd/system/{{ service_name }}.service"
    - name: reload daemon, enable and start spc
      ansible.builtin.systemd_service:
        name: "{{ service_name }}"
        daemon_reload: yes
        enabled: yes
        state: started
    
