---
- name: install and configure nop commerce
  hosts: app
  become: yes
  roles:
    - name: install nop
      role: "roles/nop"
- name: configure mysql database
  hosts: db
  become: yes
  roles:
    - name: install mysql
      role: buluma.mysql
      mysql_port: 3306
      mysql_bind_address: "0.0.0.0"
      mysql_databases:
        - name: nopdb
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: nop
          password: nopnopnop
          priv: "*.*:ALL,GRANT"
          update_password: on_create
          host: "%"
          
      
    

    